### ISSUE TITLE
Unable to get cli arguments in app-scripts from build command

### ISSUE THREAD

**Issue by NoelDeMartin** [ionic-team/ionic-cli#1757]
#### Short description of the problem:
`ionic build` command doesn't pass cli arguments to app scripts.

#### What behavior are you expecting?
I expect cli arguments to be passed down to the app-scripts (like ionic serve does).

In order to fix this issue, I think it could be as easy as changing line 59 of file lib/ionic/build.js to:

```
npmScripts.runIonicScript('build', rawCliArguments.slice(1));
```
from the current version:

```
npmScripts.runIonicScript('build');
```

since line 71 of file lib/ionic/serve.js is currently the following:

```
npmScripts.runIonicScript('serve', rawCliArguments.slice(1));
```

**Steps to reproduce:**
1. Create new ionic 2 blank project
2. Modify file "node_modules/@ionic/app-scripts/dist/build.js" adding `console.log(process.argv);` on the first line
3. Run `ionic build android --release`
4. Observe how arguments were lost ("android" and "--release" not accesible anymore)

**Post the output of `ionic info` below please**
Cordova CLI: 6.3.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.13
Node Version: v4.4.1
Xcode version: Not installed

**Other information:**
I opened this in the forum a week ago but I got no responses, there is more context on why I would need this: https://forum.ionicframework.com/t/providing-build-configuration/71867

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Would you mind installing the latest app-scripts (npm install @ionic/app-scripts --save-dev) and the latest test cli (npm install -g ionic@test) and giving this another try? This has been fixed with the latest of the cli and app-scripts so with those versions it should work for you (:

**Comment by NoelDeMartin** [comment]
I have tried and it is an improvement, but there are still some parameters missing. With the example I was giving, I now get the following out of logging *process.argv*:

    [ '/usr/local/bin/node',
      '{path-to-project}/node_modules/.bin/ionic-app-scripts',
      'build',
      '--release',
      '--',
      '--release' ]

So while *--release* is now passed, *android* is still missing. I also checked in other variables (for example process.env which cordova hooks use to indicate the platform) but android is nowhere to be found.

**Comment by jgw96** [comment]
@NoelDeMartin Thanks for testing. So when it builds does it build the apk?

**Comment by NoelDeMartin** [comment]
It fails but it may have something to do with my local environment. I think that's outside of the scope of this issue since I can execute the *console.log(process.env)* line correctly, but in case you are interested this is the error I get:

    Error: Cannot find module 'reflect-metadata'
        at Function.Module._resolveFilename (module.js:325:15)
        at Function.Module._load (module.js:276:25)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jin/workspace/sandbox/foobar/node_modules/@ionic/    app-scripts/dist/aot/aot-compiler.js:4:1)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
    
    npm ERR! Linux 3.13.0-36-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--"     "--release"
    npm ERR! node v4.4.1
    npm ERR! npm  v2.14.20
    npm ERR! code ELIFECYCLE
    npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build "--release"`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts     build "--release"'.
    npm ERR! This is most likely a problem with the ionic-hello-world package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     ionic-app-scripts build "--release"
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs ionic-hello-world
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR! 
    npm ERR!     npm owner ls ionic-hello-world
    npm ERR! There is likely additional logging output above.

**Comment by jgw96** [comment]
Hmmm that error almost looks like you have not done an `npm install`. I would `rm -rf` your node_modules and install again. @jthoms1 how are the `--release` and `android` arguments parsed? Any reason `android` should not show up when console.logging out the arguments passed to the cli?

**Comment by NoelDeMartin** [comment]
Yeah I installed the @ionic/test locally instead of globally in order to test this, so there is probably something wrong in my local installation. Don't mind it for this issue.

**Comment by jgw96** [comment]
@NoelDeMartin Sorry for the slight delay on this. So after further research this is actually expected behavior. So with your example command `ionic build android --release` the `android` argument and the `--release` argument are both handled by cordova (which our cli wraps) instead of being parsed by app-scripts. This would be the reason that you are not seeing those arguments logged out from app-scripts. I am gonna leave this issue open as an enhancement for now as it may be possible to also pass these arguments to app-scripts.

**Comment by NoelDeMartin** [comment]
Ok, as I explained more in depth on the ionic forum post, my goal with this was to be able of building different flavors like using gradle. I understand that this is handled by cordova, but since ionic serve does not call cordova serve (but ionic build does call cordova build) I need to duplicate code and have the same thing in a cordova hook and in an app script. Since that is doable, this is not by any means a breaking issue, but I just thought everything should be handled with app scripts.

Thanks for your attention and I'll keep an eye on this if you ever have the time to look into it again :D.

**Comment by dwieeb** [comment]
@NoelDeMartin 👋 I've been cleaning up issues in this repo. 

If you're still around, perhaps you've heard some chatter about Ionic 4 using Angular CLI and tooling. At Ionic we're all-in on it for v4, instead of maintaining app-scripts. If this is still an issue, it's likely we won't go back and fix this. But I understand needing to access command line flags in custom scripts, so I'm open to issues in the future relating to how we can improve extensibility for v4 projects.

Thanks for the issue! Closing for now.
