### ISSUE TITLE
 Cannot find module 'lodash/assign'

### ISSUE THREAD

**Issue by gayathri777** [ionic-team/ionic-cli#1845]
When iam doing ionic serve returning an error

D:\Gayathri\workspace\MobileHtml>ionic serve
Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\gayathri.b\AppData\Roaming\npm\node_modules\
ionic\node_modules\xmlbuilder\lib\index.js:5:12)
    at Object.<anonymous> (C:\Users\gayathri.b\AppData\Roaming\npm\node_modules\
ionic\node_modules\xmlbuilder\lib\index.js:14:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by aperezcoinpre** [comment]
Same error here

Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\USUARIO\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:
5:12)
    at Object.<anonymous> (C:\Users\USUARIO\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:
14:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by aperezcoinpre** [comment]
Finally i fixed it with:

npm uninstall -g ionic cordova
npm cache clean
npm install -g ionic cordova

**Comment by dylanvdmerwe** [comment]
@aperezcoinpre those steps fixed the error on my side as well.

**Comment by jrivera-technisys** [comment]
Thanks for the help, but it didn't help on my side. I can't even run ionic info because it throws the same "cannot find module 'lodash/assign', here's the full error: 

_Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:5:12)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:14:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)_

Thanks in advance for your help.

**Comment by jimwheaton** [comment]
Same issue here. Steps proposed by @aperezcoinpre  did not fix the issue.

**Comment by jimwheaton** [comment]
Fixed the issue by completely removing node and npm (http://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows) and reinstalling node. I think my npm cache in my user profile must have been corrupt somehow.

**Comment by JacobbV** [comment]
@jrivera-technisys @jimwheaton, Look if this works

npm i --save lodash.assign

**Comment by jimwheaton** [comment]
@JacobbV Thanks for the suggestion, but I tried that with no success. As mentioned in my last comment, I was able to fix the issue by completely wiping node/npm and reinstalling. I suspect it was an npm cache issue.

**Comment by rodrigodrds** [comment]
Same erro here
_Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\rodrigo.dias.CO\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:5:12)
    at Object.<anonymous> (C:\Users\rodrigo.dias.CO\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:14:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)_

**Comment by maseehkat** [comment]
Hello

If anyone else is still having this problem, this worked for me:
1. Uninstall Ionic
`npm uninstall -g ionic cordova`

2. Uninstall Node
3. Reinstall Node (I downloaded the latest version)
4. Clear cache
`npm cache clean`

5. Reinstall Ionic
`npm install -g ionic cordova`

That worked for me. I tried the exact same thing but without uninstalling Node first and it didn't work.

Thanks to @aperezcoinpre 💯 
Hope this helps
