### ISSUE TITLE
TypeError: env.runcmd is not a function

### ISSUE THREAD

**Issue by Barathwaja** [ionic-team/ionic-cli#2746]
After uninstalling completely and installed a downgraded version v.3.2.0 ionic says the following error while using cmd **ionic serve** or **ionic cordova build android**.
Huge error in ionic v3.6 cli so downgraded but yet i couldnt build any.

Kind Request.

Release a **stable one** and make **other versions as beta** because when upgrading other Components or ionic-native affected.

Screenshot - 
![screenshot-2017-9-19 screenshot from 2017-09-19 01-59-06 png png image 1600 x 900 pixels - scaled 88](https://user-images.githubusercontent.com/5066436/30563198-bd699688-9cde-11e7-962f-f392e3c0ee9f.png)

**Comment by dwieeb** [comment]
@Barathwaja I'm more curious what the error in later versions of the CLI is. Please install the _latest_ CLI (3.10.3 as of time of writing) and post the full output of the error you're getting.

Please also post full errors (not images) and avoid broad topic titles to help others in SEO searchability. Many arrive here from Google. For example: https://github.com/ionic-team/ionic/issues/12561

**Comment by Barathwaja** [comment]
@dwieeb font error occurs in 3.10.3 so i've downgraded lower version.
And the link you gave worked to downgrade without that _env.runcmd error_

**npm install --save --save-exact -g ionic@x.x.x
npm install --save-dev @ionic/cli-plugin-cordova@1.4.1**

**Comment by dwieeb** [comment]
The font error is resolved by upgrading `@ionic/app-scripts`. We've fixed each of these issues you're getting. Please stay up to date. Use tools like `npm outdated` and `npm upgrade`.

**Comment by Barathwaja** [comment]
@dwieeb thanks mate ..

**Comment by dwieeb** [comment]
@Barathwaja Actually I'm not sure if the fix in `@ionic/app-scripts` is out yet. Maybe try the nightly? My apologies, there are a lot of things happening at once!

**Comment by Barathwaja** [comment]
@dwieeb no issues. I've asked one person aboutt nightly is perfect. Just now checked Ionic-CLI 3.12 still its not fixed. If app-scripts nightly works I'll update it.

Yea Yea for past two years I've been using ionic never saw this much errors. Please check and deploy. and the **prod release** is awesome app size is really **minimized**.
